name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Build application
        run: |
          pyinstaller --noconfirm medusa.spec
          cd release
          zip -r medusa_tools_${{ github.ref_name }}_macos.zip "Medusa Wavetable Utility"
          
      - name: Generate release notes
        run: |
          python tools/version_manager.py notes ${GITHUB_REF#refs/tags/v} > RELEASE_NOTES.md
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/medusa_tools_${{ github.ref_name }}_macos.zip
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: actions/github-script@v7
        with:
          script: |
            const release = context.ref.replace('refs/tags/', '')
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              body: `🎉 Version ${release} has been released! Check it out at https://github.com/${context.repo.owner}/${context.repo.repo}/releases/tag/${release}`
            })