name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: Install ffmpeg
        run: |
          brew install ffmpeg

      - name: Verify ffmpeg installation
        run: |
          if [ ! -f "/opt/homebrew/bin/ffmpeg" ]; then
            echo "ffmpeg not found at /opt/homebrew/bin/ffmpeg"
            exit 1
          fi

      - name: Build CLI tool
        run: |
          pyinstaller --name medusa_cli --onefile medusa_cli.py
          cd dist
          zip -r medusa_cli_${{ github.ref_name }}_macos.zip medusa_cli
          cd ..
          
      - name: Build GUI app
        run: |
          pyinstaller --clean medusa.spec
          cd dist
          zip -r "Medusa Wavetable Utility_${{ github.ref_name }}_macos.zip" "Medusa Wavetable Utility.app"
          cd ..
          
      - name: Generate release notes
        run: |
          python tools/version_manager.py notes ${GITHUB_REF#refs/tags/v} > RELEASE_NOTES.md
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/medusa_cli_${{ github.ref_name }}_macos.zip
            dist/Medusa Wavetable Utility_${{ github.ref_name }}_macos.zip
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}